version: '3.4'

services:
  unitagram.webapi:
    container_name: unitagram.webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Default=Server=unitagram.db;Database=UnitagramDb;User Id=admin;Password=admin1234"
    ports:
      - "8000:80"
    depends_on: 
      - unitagram.db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  unitagram.db:
    container_name: unitagram.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=UnitagramDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - unitagram_data:/var/lib/postgresql/data/
      
  unitagram.identity.db:
    container_name: unitagram.identity.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=UnitagramIdentityDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - unitagram_identity_data:/var/lib/postgresql/data/
      
  identity.db:
    container_name: identity.db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Identity
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - identity_data:/var/lib/postgresql/data/
        
  unitagram.identity:
    container_name: unitagram.identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/unitagram-realm-export.json
      - DB_VENDOR=POSTGRES
      - DB_ADDR=unitagram.identity.db
      - DB_DATABASE=UnitagramIdentityDb
      - DB_USER=admin
      - DB_PASSWORD=admin1234
    volumes:
      - unitagram_identity:/opt/jboss/keycloak/standalone/data
      - ./unitagram-realm-export.json:/tmp/unitagram-realm-export.json
    ports:
      - "8010:8080"
