version: '3.4'

services:
  unitagram.webapi:
    image: ${DOCKER_REGISTRY-}unitagramwebapi
    build:
      context: .
      dockerfile: main/src/API/Unitagram.WebAPI/Dockerfile
      
  unitagram.db:
    image: postgres
      
  unitagram.identity.db:
    image: postgres
    
  unitagram.identity:
    image: jboss/keycloak:latest
    
    
volumes: 
  unitagram_data:
  unitagram_identity:
  unitagram_identity_data:
