//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitagram.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unitagram.Infrastructure.Localization.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data conflict error during update..
        /// </summary>
        internal static string Identity_ConcurrencyFailure {
            get {
                return ResourceManager.GetString("Identity.ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error..
        /// </summary>
        internal static string Identity_DefaultError {
            get {
                return ResourceManager.GetString("Identity.DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already associated with an account..
        /// </summary>
        internal static string Identity_DuplicateEmail {
            get {
                return ResourceManager.GetString("Identity.DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eole name already exists..
        /// </summary>
        internal static string Identity_DuplicateRoleName {
            get {
                return ResourceManager.GetString("Identity.DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username already exists..
        /// </summary>
        internal static string Identity_DuplicateUserName {
            get {
                return ResourceManager.GetString("Identity.DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified email is invalid..
        /// </summary>
        internal static string Identity_InvalidEmail {
            get {
                return ResourceManager.GetString("Identity.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Role name is invalid..
        /// </summary>
        internal static string Identity_InvalidRoleName {
            get {
                return ResourceManager.GetString("Identity.InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        internal static string Identity_InvalidToken {
            get {
                return ResourceManager.GetString("Identity.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username is invalid..
        /// </summary>
        internal static string Identity_InvalidUserName {
            get {
                return ResourceManager.GetString("Identity.InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login is already associated with an account..
        /// </summary>
        internal static string Identity_LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("Identity.LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Incorrect password..
        /// </summary>
        internal static string Identity_PasswordMismatch {
            get {
                return ResourceManager.GetString("Identity.PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a numeric character..
        /// </summary>
        internal static string Identity_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a lowercase letter..
        /// </summary>
        internal static string Identity_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a non-alphanumeric character..
        /// </summary>
        internal static string Identity_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet the minimum number of unique characters..
        /// </summary>
        internal static string Identity_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain an uppercase letter..
        /// </summary>
        internal static string Identity_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet minimum length requirements..
        /// </summary>
        internal static string Identity_PasswordTooShort {
            get {
                return ResourceManager.GetString("Identity.PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in redeeming recovery code..
        /// </summary>
        internal static string Identity_RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("Identity.RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password..
        /// </summary>
        internal static string Identity_UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("Identity.UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already in the specified role..
        /// </summary>
        internal static string Identity_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("Identity.UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User lockout is not enabled..
        /// </summary>
        internal static string Identity_UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("Identity.UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in the specified role..
        /// </summary>
        internal static string Identity_UserNotInRole {
            get {
                return ResourceManager.GetString("Identity.UserNotInRole", resourceCulture);
            }
        }
    }
}
