//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitagram.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unitagram.Infrastructure.Localization.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again in {0} minutes later..
        /// </summary>
        internal static string AccountLockout {
            get {
                return ResourceManager.GetString("AccountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password can&apos;t be blank.
        /// </summary>
        internal static string ConfirmPasswordCantBlank {
            get {
                return ResourceManager.GetString("ConfirmPasswordCantBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email has already been confirmed successfully!.
        /// </summary>
        internal static string EmailAlreadyConfirmedException {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email can not be blank..
        /// </summary>
        internal static string EmailCantBlank {
            get {
                return ResourceManager.GetString("EmailCantBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is not correct. You have got {0} left..
        /// </summary>
        internal static string EmailInvalidCodeException {
            get {
                return ResourceManager.GetString("EmailInvalidCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email should be in a proper email address format.
        /// </summary>
        internal static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not found. Please resend code..
        /// </summary>
        internal static string EmailOtpNotFoundException {
            get {
                return ResourceManager.GetString("EmailOtpNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data conflict error during update..
        /// </summary>
        internal static string Identity_ConcurrencyFailure {
            get {
                return ResourceManager.GetString("Identity.ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error..
        /// </summary>
        internal static string Identity_DefaultError {
            get {
                return ResourceManager.GetString("Identity.DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already associated with an account..
        /// </summary>
        internal static string Identity_DuplicateEmail {
            get {
                return ResourceManager.GetString("Identity.DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eole name already exists..
        /// </summary>
        internal static string Identity_DuplicateRoleName {
            get {
                return ResourceManager.GetString("Identity.DuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username already exists..
        /// </summary>
        internal static string Identity_DuplicateUserName {
            get {
                return ResourceManager.GetString("Identity.DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified email is invalid..
        /// </summary>
        internal static string Identity_InvalidEmail {
            get {
                return ResourceManager.GetString("Identity.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Role name is invalid..
        /// </summary>
        internal static string Identity_InvalidRoleName {
            get {
                return ResourceManager.GetString("Identity.InvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        internal static string Identity_InvalidToken {
            get {
                return ResourceManager.GetString("Identity.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username is invalid..
        /// </summary>
        internal static string Identity_InvalidUserName {
            get {
                return ResourceManager.GetString("Identity.InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login is already associated with an account..
        /// </summary>
        internal static string Identity_LoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("Identity.LoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Incorrect password..
        /// </summary>
        internal static string Identity_PasswordMismatch {
            get {
                return ResourceManager.GetString("Identity.PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a numeric character..
        /// </summary>
        internal static string Identity_PasswordRequiresDigit {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a lowercase letter..
        /// </summary>
        internal static string Identity_PasswordRequiresLower {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain a non-alphanumeric character..
        /// </summary>
        internal static string Identity_PasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet the minimum number of unique characters..
        /// </summary>
        internal static string Identity_PasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain an uppercase letter..
        /// </summary>
        internal static string Identity_PasswordRequiresUpper {
            get {
                return ResourceManager.GetString("Identity.PasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet minimum length requirements..
        /// </summary>
        internal static string Identity_PasswordTooShort {
            get {
                return ResourceManager.GetString("Identity.PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in redeeming recovery code..
        /// </summary>
        internal static string Identity_RecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("Identity.RecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already has a password..
        /// </summary>
        internal static string Identity_UserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("Identity.UserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already in the specified role..
        /// </summary>
        internal static string Identity_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("Identity.UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User lockout is not enabled..
        /// </summary>
        internal static string Identity_UserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("Identity.UserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in the specified role..
        /// </summary>
        internal static string Identity_UserNotInRole {
            get {
                return ResourceManager.GetString("Identity.UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account login information is invalid..
        /// </summary>
        internal static string InvalidAccountCredentials {
            get {
                return ResourceManager.GetString("InvalidAccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username, please change your username..
        /// </summary>
        internal static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait for {0} minutes before attempting to create new code again..
        /// </summary>
        internal static string OtpCodeTryAgainLaterException {
            get {
                return ResourceManager.GetString("OtpCodeTryAgainLaterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter..
        /// </summary>
        internal static string PasswordContainLowercase {
            get {
                return ResourceManager.GetString("PasswordContainLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter..
        /// </summary>
        internal static string PasswordContainUppercase {
            get {
                return ResourceManager.GetString("PasswordContainUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be maximum of 50 characters..
        /// </summary>
        internal static string PasswordMaxChar {
            get {
                return ResourceManager.GetString("PasswordMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be maximum of 50 characters long.
        /// </summary>
        internal static string PasswordMaxLength {
            get {
                return ResourceManager.GetString("PasswordMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be minimum 8 characters long.
        /// </summary>
        internal static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre ve şifreyi onayla eşleşmiyor..
        /// </summary>
        internal static string PasswordNotEquals {
            get {
                return ResourceManager.GetString("PasswordNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password shouldn&apos;t be empty..
        /// </summary>
        internal static string PasswordShouldntEmpty {
            get {
                return ResourceManager.GetString("PasswordShouldntEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number should contain only digits..
        /// </summary>
        internal static string PhoneNumberOnlyDigit {
            get {
                return ResourceManager.GetString("PhoneNumberOnlyDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached maximum code usage. Please resend code again..
        /// </summary>
        internal static string ReachedMaximumCodeUsageException {
            get {
                return ResourceManager.GetString("ReachedMaximumCodeUsageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token can&apos;t be empty. Please log in again..
        /// </summary>
        internal static string TokenNotEmpty {
            get {
                return ResourceManager.GetString("TokenNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no university for given domain..
        /// </summary>
        internal static string UniversityDomainNotFound {
            get {
                return ResourceManager.GetString("UniversityDomainNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account login information is invalid..
        /// </summary>
        internal static string User_InvalidCredentials {
            get {
                return ResourceManager.GetString("User.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be maximum of 100 characters..
        /// </summary>
        internal static string UsernameMaxChar {
            get {
                return ResourceManager.GetString("UsernameMaxChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be maximum of 15 characters long.
        /// </summary>
        internal static string UsernameMaxLength {
            get {
                return ResourceManager.GetString("UsernameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should be minimum 4 characters long.
        /// </summary>
        internal static string UsernameMinLength {
            get {
                return ResourceManager.GetString("UsernameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username not found..
        /// </summary>
        internal static string UsernameNotFound {
            get {
                return ResourceManager.GetString("UsernameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username shouldn&apos;t be empty..
        /// </summary>
        internal static string UsernameShouldntEmpty {
            get {
                return ResourceManager.GetString("UsernameShouldntEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
